services:
  todo.database:
    image: postgres:latest
    container_name: todo.database
    restart: always
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5   

  todo.api:
    image: ${DOCKER_REGISTRY-}todoapi
    container_name: todo.api
    build:
      context: .
      dockerfile: Backend/To-do_list_api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ConectionsStrings:Host=todo.database;Database=todo_db;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
    depends_on:
      todo.database:
        condition: service_healthy
     
volumes:
  postgres_data:

